### ISSUE TITLE
Update Tutorials to Match New NEON Data

### ISSUE THREAD

**Issue by mjones01** [NEONScience/NEON-Data-Skills#171]
Many of these tutorials are built on data using older NEON file structures. 
Options: 

* update the associated data and the tutorial to match current file structures as they should now be (more) stable. 
* make notes at the top of each tutorial for which structure no longer matches the data on data.neonscience.org
* do nothing.

**Comment by cklunch** [comment]
Donal wrapped up remote sensing data format updates, I think we're all good here.
