### ISSUE TITLE
Add Actual precip data to RHDF5 lesson 

### ISSUE THREAD

**Issue by lwasser** [NEONScience/NEON-Data-Skills#22]
Rather than making up some data - it would be good to import a csv and add it to the H5 file.

Also add a "create HDF5 lesson" part one that is very simple.
1. import a csv.
2. create the H5 file
3. add the csv to the H5 file
4. add some metadata to the H5 file

Done.

Have the looping be optional part 2. it's way too complicated as written

**Comment by neondataskills** [comment]
Not yet addressed. This tutorial: http://neondataskills.org/HDF5/Create-HDF5-In-R/
