### ISSUE TITLE
When the site is forked, the CNAM and config files are copied

### ISSUE THREAD

**Issue by lwasser** [NEONScience/NEON-Data-Skills#28]
We need a way to ignore changes to those files so i can keep them current in my repo but they aren't pushed back with changes from other repos

**Comment by lwasser** [comment]
Issue one -- when a file, like CNAME is changed, git will try to add the changes to the push. if you ignore it AFTER you've added it to the tracking history, it will still be tracked. You have to delete the cache for the file

git rm --cached CNAME
Git commit
Git push

BUT how does that work across repos?

**Comment by mjones01** [comment]
This will be resolved upon the transition of the content to NEONScience.org/resources/ .  Can close issue when that is complete.

**Comment by mjones01** [comment]
No longer an issue with the deleting of the website and CNAME file.
