### ISSUE TITLE
Comments on newest versions or lessons for ESA

### ISSUE THREAD

**Issue by natalie-robinson** [NEONScience/NEON-Data-Skills#43]
Raster Data in R:
- [ ] How difficult would it be to take the NLCD class graphic at the beginning and add a blowup of one small region that shows the actual grid at finer scale (e.g., exampleGraphic.ppt emailed)?
- [ ] Typo right after UTM graphic: You can also view the rasters min and max values and the range of values _containes_ within the pixels.

Create  Canopy Height Model:
- [ ] Good link to differences between DSM/DTM/DEM: https://imageryspeaks.wordpress.com/2011/12/20/dem-versus-dtm-versus-dsm/
- [ ] All of the following is commented out (I can't include the hashtags here or the font gets all weird in the issue):

"Create a function that subtracts one raster from another
canopyCalc <- function(x, y) {
  return(x - y)
 }

use the function to create the final CHM
then plot it.
You could use the overlay function here 
chm <- overlay(dsm,dtm,fun = canopyCalc) 
but you can also perform matrix math to get the same output.
chm <- canopyCalc(dsm,dtm)" 

It is actually a bit confusing as it follows the simplest way to do the calculation (dsm-dtm). Why not simplify and delete this?
- [ ] In the intro paragraph to part 2 you have a typo in "To figure tihs out"
- [ ] There needs to be a bit more background on: 1) why you're using both vst and tree height data, and what vst data actually are; 2) why you calculate the max height for each plot for the comparison, as opposed to just getting the height measurement at the pixel corresponding to the CHM measurement and comparing that to the CHM measurement. 
- [ ] Your description of calculating data from plots mentions circular plots but the graphic shows square plots (until variation 3 at least, but it might be more intuitive to talk about circular plots until you introduce the code to make square buffers)...
- [ ] In variation 2, why is the code commented out?
- [ ] The commented out code for calculating max stem height in option 2 does not work, because the object 'insitu_inCentroid$stemheight is not recognized (it's used throughout the code block).

Intro do HDF5:
- [ ] Maybe a bit more brief intro on what HDF5 _is_ and why we would want to use it (e.g., a regular directory on your hard drive can also store heterogeneous datasets, what is the impotous for an HDF5 file?)
- [ ] Just a preference, but to me it might make more sense to assign hdf attributes with the name first, then the attribute. Like: h5writeAttribute(did2,name="Location",attr="SJER"). Not a big deal, it just seems a little more intuitive to name the thing first.

**Comment by mjones01** [comment]
It appears that these comments have been addressed at some point in the past.  Closing issue.
