### ISSUE TITLE
Join function in pheno-time series tutorial

### ISSUE THREAD

**Issue by KathleenRuth** [NEONScience/NEON-Data-Skills#455]
Hello,

I'm coming up with this warning message when I try to join data frames. I don't know what this means or if the command was successful..

> # Create a new dataframe "phe_ind" with all the data from status and some from ind_lastnoD
> phe_ind <- left_join(status_noD, ind_lastnoD)
Joining, by = c("namedLocation", "domainID", "siteID", "plotID", "individualID")
Warning messages:
1: Column `namedLocation` joining character vector and factor, coercing into character vector 
2: Column `domainID` joining character vector and factor, coercing into character vector 
3: Column `siteID` joining character vector and factor, coercing into character vector 
4: Column `plotID` joining character vector and factor, coercing into character vector 
5: Column `individualID` joining character vector and factor, coercing into character vector

**Comment by gklarenberg** [comment]
The warning message seems to imply that the variables are characters in one dataframe, and vectors in the other. When joining, they're all forced to be characters in the new dataframe.
So it seems the joining went fine, but if you want to get rid of the warning, check what data type those variables are in the dataframes you're merging.
