### ISSUE TITLE
Where do people start

### ISSUE THREAD

**Issue by lwasser** [NEONScience/NEON-Data-Skills#53]
Community Feedback: 
"My one problem is there's no real guidance on recommended order (if there is one). I'm not really sure where to get started or if there is even any sort of linear path through all of the lessons.  It might benefit from a "start here", especially for those that are new to all of the topics."

---

We need to address the use case of those coming to the site who don't necessarily have a path in mind, but want to start working with data. Perhaps we create a few lesson set "workshop" like pages as a test?

**Comment by lwasser** [comment]
Another comment - when we are holding workshops, etc! We should have a calendar page or something with upcoming events.

**Comment by mjones01** [comment]
Closing this issue as it will be addressed with the move to NEONScience.org.
