### ISSUE TITLE
HDF5 Hyperspectral Lesson - Subset doesn't match our distribution

### ISSUE THREAD

**Issue by lwasser** [NEONScience/NEON-Data-Skills#56]
See comments:
http://neondataskills.org/HDF5/Imaging-Spectroscopy-HDF5-In-R/#comment-2479441671

The data subset is an OLDER version of the H5 file. Thus the code is not helping our user community. We need to 
1. Ask josh to create a new subset that exactly mimicks the H5 file format we are distributing now.
2. redo this lesson to match our current format.

**Comment by mjones01** [comment]
@donal-at-NEON - this will up corrected when the current PRs are merged, yes?

**Comment by donal-at-NEON** [comment]
Yes, this issue should be resolved once the PR is merged.
