### ISSUE TITLE
Global Environment Disapeared

### ISSUE THREAD

**Issue by KathleenRuth** [NEONScience/NEON-Data-Skills#591]
I'm not sure I'm leaving this in the correct spot but my global environment disappeared & the subsequent data sets show as "object no longer exists" 

I tried reloading my ".RData" file into my workspace but that hasn't yielded anything. See below: 

[Workspace loaded from ~/School/Research/RMNP Phenology Temp/RMNP Gymno Phenology Temp/.RData]

> load("~/School/Research/RMNP Phenology Temp/RMNP Gymno Phenology Temp/.RData")

I was in the process of working through the below code from the Pheno-Temp Tutorial and my global environment vanished. 

quality flags
> ```{r qf-data}
> finalQf
Error: object 'finalQf' not found
> sum(YELL.Pheno$finalQF)
[1] 0
> sum(RMNP.Temp1$finalQf)
[1] 0

What about null (`NA`) data? 
  ```{r na-data}
# Are there NA's in your data? Count 'em up
> sum(is.na(RMNP.Temp1$tempSignleMean))
[1] 0
> # Are there NA's in your data? Count 'em up
> sum(is.na(YELL.Temp$tempSingleMean))
[1] 0

na.rm=TRUE 
  **tells R to ignore n/a values when making calculations

# create new dataframe without NAs
YELL.Temp_noNA <- YELL.Temp 
  drop_na(tempSingleMean)  # tidyr function
RMNP.Temp_noNA <- RMNP.Temp1
  drop_NA(tempSingleMean)
  
  > sum(is.na(YELL.Temp_noNA$tempSingleMean))
[1] 0
> sum(is.na(RMNP.Temp1_noNA$tempSingleMean))
Error: object 'RMNP.Temp1_noNA' not found
> sum(is.na(RMNP.Temp_noNA$tempSingleMean))
[1] 0

**Comment by donal-at-NEON** [comment]
Hi @KathleenRuth , thank you for your message. I am happy to see that you are working with NEON data, and will be happy to help resolve this issue. I have conferred with my colleague, @cklunch, and we have not been able to reproduce this error. Could you try it again to see if you can replicate? Let us know how it goes, and if warranted, I will be happy to meet with you to see if we can troubleshoot the issue.
