### ISSUE TITLE
curly bracket placement issue for automated script testing

### ISSUE THREAD

**Issue by natalie-robinson** [NEONScience/NEON-Data-Skills#610]
@cklunch, can you move the opening curly bracket for a function onto the same line as the function call, as described below? My automated testing script needs to identify functions and this is very difficult if the curly bracket is not on the same line as the call.

Thank you!

File: ~tutorials/R/Geospatial-skills/primer-raster-r/Creating-Square-Plot-Boundaries-From-Centroids-in-R/Creating-Square-Plot-Boundaries-From-Centroids-in-R.R (and associated rmd, html, etc. files)

Line: 55

OLD code:
  polys <- SpatialPolygons(mapply(function(poly, id)
        {
	  xy <- matrix(poly, ncol=2, byrow=TRUE)
	  Polygons(list(Polygon(xy)), ID=id)
	}, 
	split(square, row(square)), ID),
	proj4string=CRS(as.character("+proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")))

NEW code request:
   polys <- SpatialPolygons(mapply(function(poly, id){
	  xy <- matrix(poly, ncol=2, byrow=TRUE)
	  Polygons(list(Polygon(xy)), ID=id)
	}, 
	split(square, row(square)), ID),
	proj4string=CRS(as.character("+proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")))

I am also happy to make the change and submit a PR, I just need to quickly walk through the procedure for creating all the files properly.

**Comment by cklunch** [comment]
@natalie-robinson Happy to, this is an easy change and I can see it would help. Is the example above the only instance where it's happening, or are there more?

I might just go in and change it manually, depending on how common this is.

**Comment by natalie-robinson** [comment]
@cklunch - I don't know how common yet, but will keep you posted as I work through more of the files. My suspicion is this isn't that common!

**Comment by cklunch** [comment]
@natalie-robinson OK cool. Updated for the tutorial you identified!
