### ISSUE TITLE
Mapping/shapefile Learning Hub tutorials rely on archived R package

### ISSUE THREAD

**Issue by kyule** [NEONScience/NEON-Data-Skills#698]
Hi all-

I was hoping to find a Learning hub tutorial for making nice maps of the NEON sites in R (e.g. show the continental scale with a "minichart" of some data I'm interested in over each site). I came across some of the shapefile tutorials that definitely had some useful info, but they rely on the deprecated rgdal package. Maybe those can be easily updated to use newer generation packages. Additionally, if there was a tutorial to lower the barrier to entry for making "prettier" maps, I know that at least I would use it :) 

Thanks!
Kelsey

**Comment by gklarenberg** [comment]
Hi @kyule, I don't work for NEON but use their data in a lot of my teaching. Just as an FYI, the geospatial curriculum from The Carpentries also uses NEON data and they have recently updated all their resources to use `terra` and `sf` (and `tidyverse`): see https://datacarpentry.org/geospatial-workshop/ for an overview and https://datacarpentry.org/r-raster-vector-geospatial/ for the lessons (if you click somewhere on the left, a bar will fold out showing all the lessons)

**Comment by kyule** [comment]
@gklarenberg - Awesome, I will definitely check this out.

**Comment by cklunch** [comment]
@kyule Thanks for the heads up! @gklarenberg Thanks for the tip for alternatives.
I'll take a look at the Carpentries lessons and either update the NEON tutorial or redirect users to the Carpentries.

**Comment by cklunch** [comment]
The NEON maps tutorial is now updated to use the `sf` package. Thanks for your patience!

**Comment by cklunch** [comment]
The NEON maps tutorial is now updated to use the `sf` package. Thanks for your patience!
